name: helD
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.6
  - bioconda::snakemake-minimal>=5.22.1
  - bioconda::ete3
  - bioconda::biopython
  - bioconda::ncbi-genome-download
  - bioconda::mafft
  - bioconda::krona
  - bioconda::iqtree