name: helD
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.6
  - bioconda::snakemake-minimal==6.0.5
  - bioconda::ete3
  - bioconda::biopython
  - bioconda::ncbi-genome-download
  - bioconda::diamond
  - bioconda::hmmer
  - bioconda::mafft
  - bioconda::krona
  - bioconda::iqtree
  - bioconda::fasttree
